var events = [
  {
    "Member": "Kyrsten Sinema",
    "Party": "Democratic",
    "State": "AZ",
    "District": "AZ-9",
    "meetingType": "District Office Hours",
    "Date": "Feb-1",
    "Time": "10:00 AM",
    "Location": "Acacia Branch Library",
    "streetNumber": 750,
    "streetName": "E. Townley Ave",
    "City": "Sunnyslope",
    "Zip": 85020,
    "Notes": ""
  },
  {
    "Member": "Paul Gosar",
    "Party": "Republican",
    "State": "AZ",
    "District": "AZ-4",
    "meetingType": "Town Hall",
    "Date": "Feb-23",
    "Time": "6:00 PM",
    "Location": "Best Western Hotel",
    "streetNumber": 8333,
    "streetName": "E Sunrise Sky Dr",
    "City": "Gold Canyon",
    "Zip": 85118,
    "Notes": ""
  },
  {
    "Member": "Jeff Flake",
    "Party": "Republican",
    "State": "AZ",
    "District": "",
    "meetingType": "Office Hours",
    "Date": "2/7",
    "Time": "2:00 PM",
    "Location": "Coolidge City Council Chambers",
    "streetNumber": 911,
    "streetName": "S Arizona Blvd",
    "City": "Coolidge",
    "Zip": 85128,
    "Notes": "Staff. Sen. Flake not in attendance."
  },
  {
    "Member": "Jeff Flake",
    "Party": "Republican",
    "State": "AZ",
    "District": "",
    "meetingType": "Office Hours",
    "Date": "2/8",
    "Time": "1:30 PM",
    "Location": "Sun City West",
    "streetNumber": 13815,
    "streetName": "Camino Del Sol",
    "City": "Sun City West",
    "Zip": 85375,
    "Notes": "Staff. Sen. Flake not in attendance."
  },
  {
    "Member": "Jeff Flake",
    "Party": "Republican",
    "State": "AZ",
    "District": "",
    "meetingType": "Office Hours",
    "Date": "2/9",
    "Time": "9:30 AM",
    "Location": "Gila County Board of Supervisors",
    "streetNumber": 1400,
    "streetName": "E Ash St",
    "City": "Globe",
    "Zip": 85501,
    "Notes": "Staff. Sen. Flake not in attendance."
  },
  {
    "Member": "Jeff Flake",
    "Party": "Republican",
    "State": "AZ",
    "District": "",
    "meetingType": "Office Hours",
    "Date": "2/9",
    "Time": "1:30 PM",
    "Location": "Apache Junction Library",
    "streetNumber": 1177,
    "streetName": "N Idaho Road",
    "City": "Apache Junction",
    "Zip": 85119,
    "Notes": "Staff. Sen. Flake not in attendance."
  },
  {
    "Member": "Jeff Flake",
    "Party": "Republican",
    "State": "AZ",
    "District": "",
    "meetingType": "Office Hours",
    "Date": "2/7",
    "Time": "9:30 AM",
    "Location": "Pinal County Administrative Complex",
    "streetNumber": 135,
    "streetName": "N Pinal St",
    "City": "Florence",
    "Zip": 85132,
    "Notes": "Staff. Sen. Flake not in attendance."
  },
  {
    "Member": "Jackie Speier",
    "Party": "Democratic",
    "State": "CA",
    "District": "CA-14",
    "meetingType": "Town Hall",
    "Date": "2/11",
    "Time": "11:00 AM",
    "Location": "Place Lowell High School - Carol Channing theater",
    "streetNumber": 1101,
    "streetName": "Eucalyptus Ave",
    "City": "San Francisco",
    "Zip": 94132,
    "Notes": "Lowell High School PTSA invites you to attend when Congresswomen Jackie Speier has a \"Conversation about America\" with people who have questions about the changes that are confronting us."
  },
  {
    "Member": "Tom McClintock",
    "Party": "Republican",
    "State": "CA",
    "District": "CA-4",
    "meetingType": "Town Hall",
    "Date": "Feb-4",
    "Time": "10:00 AM",
    "Location": "Tower Theatre",
    "streetNumber": 417,
    "streetName": "Vernon Street",
    "City": "Roseville",
    "Zip": 95678,
    "Notes": ""
  },
  {
    "Member": "Jody Hice",
    "Party": "Republican",
    "State": "GA",
    "District": "",
    "meetingType": "Mobile Office Hours",
    "Date": "2/10",
    "Time": "10:00 AM",
    "Location": "Green County Farm Bureau",
    "streetNumber": 1570,
    "streetName": "S. Main Street",
    "City": "Greensboro",
    "Zip": 30642,
    "Notes": "In an ongoing effort to provide excellent constituent services, Congressman Jody Hice (GA-10) will host Mobile Office Hours with two opportunities for 10th District residents to meet with his staff in February. Mobile Office Hours provides residents who are unable to visit the Congressman’s office because of time or location restrictions the opportunity to meet with a knowledgeable member of his staff to discuss their concerns, share their priorities, or seek help with a federal agency. (Staff from Sen. Isakson and Sen. Perdue's offices will also be present)"
  },
  {
    "Member": "Andy Barr",
    "Party": "Republican",
    "State": "KY",
    "District": "KY-6",
    "meetingType": "District Office Hours",
    "Date": "Feb-1",
    "Time": "9:00 AM",
    "Location": "Wolf County Courthouse",
    "streetNumber": 10,
    "streetName": "Court Street",
    "City": "Campton",
    "Zip": 41301,
    "Notes": "This is a regularly occuring meeting that will continue to take place the first Wednesday of each month."
  },
  {
    "Member": "Andy Barr",
    "Party": "Republican",
    "State": "KY",
    "District": "KY-6",
    "meetingType": "District Office Hours",
    "Date": "Feb-1",
    "Time": "1:00 PM",
    "Location": "Menifee County Courthouse",
    "streetNumber": 12,
    "streetName": "Main Street",
    "City": "Frenchburg",
    "Zip": 40322,
    "Notes": "This is a regularly occuring meeting that will continue to take place the first Wednesday of each month."
  },
  {
    "Member": "Andy Barr",
    "Party": "Republican",
    "State": "KY",
    "District": "KY-6",
    "meetingType": "District Office Hours",
    "Date": "Feb-1",
    "Time": "3:00 PM",
    "Location": "Clark County-Winchester City Hall",
    "streetNumber": 32,
    "streetName": "Wall Street",
    "City": "Winchester",
    "Zip": 40392,
    "Notes": "This is a regularly occuring meeting that will continue to take place the first Wednesday of each month."
  },
  {
    "Member": "Ralph Abraham",
    "Party": "Republican",
    "State": "LA",
    "District": "LA-5",
    "meetingType": "District Office Hours",
    "Date": "Feb-2",
    "Time": "9:00 AM",
    "Location": "Lincoln Parish Courthouse ground floor conference room",
    "streetNumber": 100,
    "streetName": "W. Texas St",
    "City": "Ruston",
    "Zip": 71270,
    "Notes": "This is a regularly occuring event that will take place on the first Tuesday of ever month."
  },
  {
    "Member": "Ralph Abraham",
    "Party": "Republican",
    "State": "LA",
    "District": "LA-5",
    "meetingType": "District Office Hours",
    "Date": "Feb-9",
    "Time": "9:00 AM",
    "Location": "Grant Parish Police Jury meeting room",
    "streetNumber": 200,
    "streetName": "Main Street",
    "City": "Colfax",
    "Zip": 71417,
    "Notes": "This is a regularly occuring meeting that will continue to take place the second Tuesday of each month."
  },
  {
    "Member": "Ralph Abraham",
    "Party": "Republican",
    "State": "LA",
    "District": "LA-5",
    "meetingType": "District Office Hours",
    "Date": "Feb-9",
    "Time": "1:00 PM",
    "Location": "Winn Parish Police Jury meeting room 112",
    "streetNumber": 119,
    "streetName": "W. Main Street, No. 102",
    "City": "Winnfield",
    "Zip": 71483,
    "Notes": "This is a regularly occuring meeting that will continue to take place the second Tuesday of each month."
  },
  {
    "Member": "Angus King",
    "Party": "Independent",
    "State": "",
    "District": "",
    "meetingType": "D.C. Coffee",
    "Date": "Every Wednesday",
    "Time": "9:00 AM",
    "Location": "Hart Senate Office Building",
    "streetNumber": 133,
    "streetName": "Hart Senate Office Building",
    "City": "Washington D.C.",
    "Zip": 20002,
    "Notes": ""
  },
  {
    "Member": "Jim McGovern",
    "Party": "Democratic",
    "State": "MA",
    "District": "MA-2",
    "meetingType": "Ticketed Event",
    "Date": "Feb-25",
    "Time": "9:00 AM",
    "Location": "The Manor Banquet Facility",
    "streetNumber": 42,
    "streetName": "W Boylston Street",
    "City": "West Boylston",
    "Zip": 1583,
    "Notes": "Worcester County Democratic Organizing Breakfast"
  },
  {
    "Member": "Tom Emmer",
    "Party": "Republican",
    "State": "MN",
    "District": "MN-6",
    "meetingType": "District Office Hours",
    "Date": "Feb-7",
    "Time": "9:30 AM",
    "Location": "Waite Park City Hall",
    "streetNumber": 19,
    "streetName": "13th Ave N",
    "City": "Waite Park",
    "Zip": 56387,
    "Notes": ""
  },
  {
    "Member": "Roger Wicker",
    "Party": "Republican",
    "State": "",
    "District": "",
    "meetingType": "D.C. Coffee",
    "Date": "Every Tuesday",
    "Time": "8:30 AM",
    "Location": "TBD",
    "streetNumber": "",
    "streetName": "",
    "City": "Washington D.C.",
    "Zip": "",
    "Notes": "Sen. Wicker meets Mississippians in D.C. every Tuesday a.m. for coffee. Email for location: coffee@wicker.senate.gov"
  },
  {
    "Member": "Deb Fischer",
    "Party": "Republican",
    "State": "NE",
    "District": "",
    "meetingType": "Office Hours",
    "Date": "2/13",
    "Time": "9:00 AM",
    "Location": "Box Butte County Courthouse",
    "streetNumber": 515,
    "streetName": "Box Butte Ave",
    "City": "Alliance",
    "Zip": 69301,
    "Notes": "Staff. Sen. Fischer not in attendance."
  },
  {
    "Member": "Deb Fischer",
    "Party": "Republican",
    "State": "NE",
    "District": "",
    "meetingType": "Office Hours",
    "Date": "2/13",
    "Time": "1:00 PM",
    "Location": "Kimball Public Library",
    "streetNumber": 208,
    "streetName": "S Walnut Street",
    "City": "Kimball",
    "Zip": 69145,
    "Notes": "Staff. Sen. Fischer not in attendance."
  },
  {
    "Member": "Nydia Velázquez",
    "Party": "Democratic",
    "State": "N/A",
    "District": "NY-7",
    "meetingType": "TeleTown Hall Meeting",
    "Date": "Feb-1",
    "Time": "7:30 PM",
    "Location": "N/A",
    "streetNumber": "N/A",
    "streetName": "N/A",
    "City": "N/A",
    "Zip": "N/A",
    "Notes": "Time & dial-in number TBA (Twitter/Website)"
  },
  {
    "Member": "Chuck Schumer",
    "Party": "Democratic",
    "State": "NY",
    "District": "NY-7",
    "meetingType": "Public Meeting",
    "Date": "2/2",
    "Time": "12:00 PM",
    "Location": "District Office",
    "streetNumber": 780,
    "streetName": "Third Ave",
    "City": "New York",
    "Zip": 10017,
    "Notes": ""
  },
  {
    "Member": "David Rouzer",
    "Party": "Republican",
    "State": "NC",
    "District": "NC-7",
    "meetingType": "District Office Hours",
    "Date": "Feb-1",
    "Time": "9:00 AM",
    "Location": "Kenansville Agricultural Center",
    "streetNumber": 165,
    "streetName": "Agriculture drive, Suite A",
    "City": "Kenansville",
    "Zip": 28349,
    "Notes": ""
  },
  {
    "Member": "Alma Adams",
    "Party": "Democratic",
    "State": "NC",
    "District": "NC-12",
    "meetingType": "District Office Hours",
    "Date": "Feb-2",
    "Time": "9:00 AM",
    "Location": "Spencer Town Hall",
    "streetNumber": 105,
    "streetName": "S. Long Street",
    "City": "Spencer",
    "Zip": 28039,
    "Notes": "Every Thursday 9 am - 12 pm"
  },
  {
    "Member": "David Rouzer",
    "Party": "Republican",
    "State": "NC",
    "District": "NC-7",
    "meetingType": "District Office Hours",
    "Date": "Feb-7",
    "Time": "9:00 AM",
    "Location": "Fremont Town Hall",
    "streetNumber": 120,
    "streetName": "East Main Street",
    "City": "Fremont",
    "Zip": 27839,
    "Notes": ""
  },
  {
    "Member": "Alma Adams",
    "Party": "Democratic",
    "State": "NC",
    "District": "NC-12",
    "meetingType": "District Office Hours",
    "Date": "Feb-7",
    "Time": "9:00 AM",
    "Location": "City Hall fo Lexington",
    "streetNumber": 28,
    "streetName": "West Center Street",
    "City": "Lexington",
    "Zip": 27292,
    "Notes": "1st and 3rd Tuesday of each month, 9 am - 11 am"
  },
  {
    "Member": "David Price",
    "Party": "Democratic",
    "State": "NC",
    "District": "NC-4",
    "meetingType": "Community Listening Session",
    "Date": "2/4",
    "Time": "2:00 PM",
    "Location": "Orange County Public Library",
    "streetNumber": 137,
    "streetName": "W Margaret Lane",
    "City": "Hillsborough",
    "Zip": 27278,
    "Notes": ""
  },
  {
    "Member": "Markwayne Mullin",
    "Party": "Republican",
    "State": "",
    "District": "OK-2",
    "meetingType": "Teletown Hall Meeting",
    "Date": "Feb-8",
    "Time": "7:00 PM",
    "Location": "**Call in (central time)**",
    "streetNumber": "",
    "streetName": "",
    "City": "",
    "Zip": "",
    "Notes": "Details to be provided closer to the date"
  },
  {
    "Member": "Sheldon Whitehouse",
    "Party": "Democratic",
    "State": "RI",
    "District": "At-Large",
    "meetingType": "Town Hall",
    "Date": "Feb-10",
    "Time": "2:00 PM",
    "Location": "Lincoln Senior Center",
    "streetNumber": 150,
    "streetName": "Jenckes Hill Road",
    "City": "Lincoln",
    "Zip": 2865,
    "Notes": "Join Senator Whitehouse and his staff at the upcoming Coffee & Conversation with Senator Whitehouse."
  },
  {
    "Member": "Tom Rice",
    "Party": "Republican",
    "State": "SC",
    "District": "SC-7",
    "meetingType": "District Office Hours",
    "Date": "Feb-1",
    "Time": "12:00 AM",
    "Location": "Cheraw Town Hall Jury Room",
    "streetNumber": 200,
    "streetName": "Market Street",
    "City": "Cheraw",
    "Zip": 29520,
    "Notes": "https://docs.google.com/document/d/1cR0IwDwaY_4S7LvCeeKBcHzkTSvTzEhMcZFnsPkYglk/edit?usp=sharing"
  },
  {
    "Member": "John Thune",
    "Party": "Republican",
    "State": "",
    "District": "",
    "meetingType": "D.C. Coffee",
    "Date": "Every Wednesday",
    "Time": "",
    "Location": "TBD",
    "streetNumber": "",
    "streetName": "",
    "City": "Washington D.C.",
    "Zip": "",
    "Notes": "Sen. John Thune, Sen. Mike Rounds, and Rep. Kristi Noem meet every Wed in D.C. Register here: http://www.thune.senate.gov/public/index.cfm/south-dakota-sunrise-coffee"
  },
  {
    "Member": "Ted Cruz",
    "Party": "Republican",
    "State": "",
    "District": "",
    "meetingType": "D.C. Coffee",
    "Date": "Every Tuesday",
    "Time": "9:30 AM",
    "Location": "TBD",
    "streetNumber": "",
    "streetName": "",
    "City": "Washington D.C.",
    "Zip": "",
    "Notes": "Sen. Cruz hosts coffee every Tuesday a.m. Senate is in session for Texans visiting D.C. To RSVP email scheduler@cruz.senate.gov with \"Texas Tuesday RSVP\" in subject line. Include full name, phone number, email address, date you will be in D.C. and number of people in group."
  },
  {
    "Member": "Jason Chaffetz",
    "Party": "Republican",
    "State": "UT",
    "District": "UT-3",
    "meetingType": "Town Hall",
    "Date": "2/9",
    "Time": "7:00 PM",
    "Location": "Cottonwood Heights City Hall",
    "streetNumber": 2277,
    "streetName": "Bengal Blvd",
    "City": "Cottonwood Heights",
    "Zip": 84121,
    "Notes": "Town Hall Meeting with Rep. Jason Chaffetz"
  },
  {
    "Member": "Dan Newhouse",
    "Party": "Republican",
    "State": "WA",
    "District": "WA-4",
    "meetingType": "District Office Hours",
    "Date": "Feb-6",
    "Time": "11:00 AM",
    "Location": "Omak City Hall",
    "streetNumber": 2,
    "streetName": "North Ash Street",
    "City": "Omak",
    "Zip": 98841,
    "Notes": "Congressman Dan Newhouse’s staff members will be available to meet with the anyone who needs help with a federal agency or has questions federal issues."
  }
]
